"""added artists

Revision ID: 028fbaa122a5
Revises: 3002dcb1c60f
Create Date: 2023-10-18 12:56:17.927196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028fbaa122a5'
down_revision = '3002dcb1c60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artists'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artists')
    # ### end Alembic commands ###
