"""added foreign keys to songs

Revision ID: 257982dccd79
Revises: 0707d88d09b7
Create Date: 2023-11-01 12:30:19.872161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257982dccd79'
down_revision = '0707d88d09b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('genre_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_songs_artist_id_artists'), 'artists', ['artist_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_songs_genre_id_genres'), 'genres', ['genre_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_songs_genre_id_genres'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_songs_artist_id_artists'), type_='foreignkey')
        batch_op.drop_column('genre_id')
        batch_op.drop_column('artist_id')

    # ### end Alembic commands ###
