"""add unique name to artist

Revision ID: 525186114e29
Revises: 257982dccd79
Create Date: 2023-11-08 12:44:44.333871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525186114e29'
down_revision = '257982dccd79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_artists_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_artists_name'), type_='unique')

    # ### end Alembic commands ###
